from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional, Dict, Any

router = APIRouter()

class Message(BaseModel):
    role: str
    content: str

class AnalyzeRequest(BaseModel):
    databaseId: str
    query: str
    context: Optional[List[Message]] = []

class ExecuteRequest(BaseModel):
    databaseId: str
    sql: str

@router.post("/analyze")
def analyze_query(req: AnalyzeRequest):
    if not req.databaseId or not req.query:
        raise HTTPException(status_code=400, detail="Missing databaseId or query")
    
    # TODO: Integrate OpenAI API using api.core.config.settings.OPENAI_API_KEY
    # This will be implemented once the LLM API is configured.
    
    # Stub response
    return {
        "sql": "SELECT * FROM sales WHERE year = EXTRACT(YEAR FROM CURRENT_DATE) - 1",
        "explanation": "This is a mock SQL query generated by Python backend. It selects all sales from the previous year.",
        "suggestions": ["Did you want to group by month?"],
        "confidence": 0.85
    }

@router.post("/execute")
def execute_query(req: ExecuteRequest):
    if not req.databaseId or not req.sql:
        raise HTTPException(status_code=400, detail="Missing databaseId or sql")
    
    # TODO: Connect to the target database and execute the query.
    # For this prototype, we'll return mock data.
    
    columns = ["month", "sales"]
    data = [
        {"month": "Jan", "sales": 1200},
        {"month": "Feb", "sales": 1500},
        {"month": "Mar", "sales": 1800}
    ]
    
    chart_config = {
        "title": {"text": "Sales Trend"},
        "tooltip": {},
        "xAxis": {"type": "category", "data": ["Jan", "Feb", "Mar"]},
        "yAxis": {"type": "value"},
        "series": [{"name": "Sales", "type": "line", "data": [1200, 1500, 1800]}]
    }

    return {
        "columns": columns,
        "data": data,
        "chartConfig": chart_config
    }
